### ISSUE TITLE
CancelledKeyException

### ISSUE THREAD

**Issue by JZWen** [xiantang/JerryMouse#34]
jdk: 1.8
url: localhost:8081/login
exception:
```java
Exception in thread "Thread-50" java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:82)
	at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:204)
	at com.github.apachefoundation.jerrymouse.network.connector.nio.NioPoller$PollerEvent.run(NioPoller.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xiantang** [comment]
fixed
